package com.epam.feel.server.mail.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.7-b01- Generated source version: 2.1
 * 
 */
@WebService (name = "MailerWS", targetNamespace = "http://ejb.ws.mailer.epam.com/")
@SOAPBinding (style = SOAPBinding.Style.RPC)
@XmlSeeAlso ({ObjectFactory.class})
public interface MailerWS {

    /**
     * 
     * @param message
     * @param sessionId
     * @param group
     * @return returns com.epam.feel.server.mail.wsclient.SimpleResponse
     */
    @WebMethod
    @WebResult (name = "SimpleResponse", partName = "SimpleResponse")
    public SimpleResponse sendMessage(@WebParam (name = "sessionId", partName = "sessionId") String sessionId,
        @WebParam (name = "message", partName = "message") Message message,
        @WebParam (name = "group", partName = "group") String group);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return returns com.epam.feel.server.mail.wsclient.SimpleResponse
     */
    @WebMethod
    @WebResult (name = "SimpleResponse", partName = "SimpleResponse")
    public SimpleResponse sendNewMessageWithRecepients(@WebParam (name = "arg0", partName = "arg0") Message arg0,
        @WebParam (name = "arg1", partName = "arg1") boolean arg1);

}
